server:
  port: 18888

spring:
  application:
    name: m-app
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    mapper:
      accept_case_insensitive_properties: true
    deserialization:
      fail-on-unknown-properties: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_demo?useUnicode=true&characterEncoding=utf-8&autoReconnectForPools=true&autoReconnect=true
    #    url: jdbc:mysql://localhost:330611/db_demo?useUnicode=true&characterEncoding=utf-8&autoReconnectForPools=true&autoReconnect=true
    username: akwei
    password: asdasd
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  #    port: 637911
  #    cluster:
  #      nodes:
  #        - localhost:70000
  #        - localhost:70010
  #        - localhost:70020

  kafka:
    bootstrap-servers: 127.0.0.1:9092
  #    bootstrap-servers: 127.0.0.1:909211

  rabbitmq:
    port: 5672
  #    port: 567211
  elasticsearch:
    rest:
      uris: http://localhost:9200
  #      uris: http://localhost:92000
  data:
    mongodb:
      uri: mongodb://iot_mapping:8a4b041e@localhost:27017/iot_mapping?authSource=admin&authMechanism=SCRAM-SHA-1
#  data:
#    elasticsearch:
#      client:
#        reactive:
#          endpoints: localhost:92000
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
#  level:
#    web: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
      group:
        custom:
          include: db